version: '3'
services:
  simiscore-legal:
    build: .   # build using Dockfile in this directory
    command: sh -c "gunicorn app.main:app 
                      --bind 0.0.0.0:80 
                      --worker-class uvicorn.workers.UvicornH11Worker 
                      --workers ${NUM_WORKERS}
                      --worker-tmp-dir /dev/shm"
    ports:
      - "${API_PORT}:80"